# Generated by Django 5.2.15 on 2026-07-18 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reconciliation', '0005_alter_matchrun_relation'),
        ('transactions', '0007_transaction_uniq_tx_source_rowhash_toko_null'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='matchresult',
            index=models.Index(fields=['bucket'], name='reconciliat_bucket_38343f_idx'),
        ),
        migrations.AddIndex(
            model_name='matchresult',
            index=models.Index(fields=['reason_code', 'bucket'], name='reconciliat_reason__70936b_idx'),
        ),
    ]
