# Generated by Django 5.2.15 on 2026-07-18 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reconciliation', '0006_matchresult_reconciliat_bucket_38343f_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toleranceprofile',
            name='amount_pct_tol',
            field=models.DecimalField(decimal_places=4, default=0, help_text='Saat ini hanya dipakai relasi Panel↔Bracket (amount_ok) — BELUM dipakai matcher uang (Panel/Bracket↔Bank).', max_digits=6),
        ),
        migrations.AlterField(
            model_name='toleranceprofile',
            name='date_direction',
            field=models.CharField(default='target_after_base', help_text='BELUM dipakai matcher mana pun — arah tanggal saat ini tertanam di engine (sisi uang >= sisi kredit). Mengubah field ini tidak berpengaruh.', max_length=30),
        ),
    ]
